### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v5.14.3 (/home/jray/rust-rocksdb/librocksdb-sys)`

### ISSUE THREAD

**Issue by jamesray1** [rust-rocksdb/rust-rocksdb#251]
I get an error when compiling librocksdb-sys v5.14.3: 

```bash
[jray@jr-dl rust-rocksdb]$ RUST_BACKTRACE=1 cargo build
   Compiling librocksdb-sys v5.14.3 (/home/jray/rust-rocksdb/librocksdb-sys)
error: failed to run custom build command for `librocksdb-sys v5.14.3 (/home/jray/rust-rocksdb/librocksdb-sys)`
process didn't exit successfully: `/home/jray/rust-rocksdb/target/debug/build/librocksdb-sys-fcf4146593b28c4f/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/result.rs:835
  10: core::ops::function::FnOnce::call_once
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1664
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:238
  11: <lazy_static::lazy::Lazy<T>>::get::{{closure}}
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:28
  12: std::sync::once::Once::call_once::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sync/once.rs:230
  13: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:397
  14: std::sync::once::Once::call_once
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sync/once.rs:230
  15: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:27
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/<::lazy_static::__lazy_static_internal macros>:12
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/<::lazy_static::__lazy_static_internal macros>:13
  16: bindgen::ensure_libclang_is_loaded
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1671
  17: bindgen::Bindings::generate
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1686
  18: bindgen::Builder::generate
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1216
  19: build_script_build::bindgen_rocksdb
             at librocksdb-sys/build.rs:34
  20: build_script_build::main
             at librocksdb-sys/build.rs:289
  21: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  24: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  25: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  26: main
  27: __libc_start_main
  28: _start
```

Which path should I set `LIBCLANG_PATH` to, or how can this be done automatically?

Steps to reproduce:
```bash
[jray@jr-dl ~]$ git clone https://github.com/rust-rocksdb/rust-rocksdb.git
# snip
$ cd rust-rocksdb
$ git submodule update --init --recursive
Submodule 'librocksdb-sys/lz4' (https://github.com/lz4/lz4.git) registered for path 'librocksdb-sys/lz4'
Submodule 'rocksdb_sys/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'librocksdb-sys/rocksdb'
Submodule 'rocksdb_sys/snappy' (https://github.com/google/snappy.git) registered for path 'librocksdb-sys/snappy'
Submodule 'librocksdb-sys/zlib' (https://github.com/madler/zlib.git) registered for path 'librocksdb-sys/zlib'
Submodule 'librocksdb-sys/zstd' (https://github.com/facebook/zstd) registered for path 'librocksdb-sys/zstd'
Cloning into '/home/jray/rust-rocksdb/librocksdb-sys/lz4'...
Cloning into '/home/jray/rust-rocksdb/librocksdb-sys/snappy'...
Cloning into '/home/jray/rust-rocksdb/librocksdb-sys/zlib'...
Cloning into '/home/jray/rust-rocksdb/librocksdb-sys/rocksdb'...
Cloning into '/home/jray/rust-rocksdb/librocksdb-sys/zstd'...
Submodule path 'librocksdb-sys/lz4': checked out 'c10863b98e1503af90616ae99725ecd120265dfb'
Submodule path 'librocksdb-sys/rocksdb': checked out '5089e121166c46956a8a21c8ef967f1896c239de'
Submodule path 'librocksdb-sys/snappy': checked out '2d99bd14d471664758e4dfdf81b44f413a7353fd'
Submodule path 'librocksdb-sys/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Submodule path 'librocksdb-sys/zstd': checked out 'f3a8bd553a865c59f1bd6e1f68bf182cf75a8f00'
$ RUST_BACKTRACE=1 cargo build

System info:
```bash
[jray@jr-dl rust-rocksdb]$ inxi -Fxz
System:    Host: jr-dl Kernel: 4.20.1-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: N/A Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: <filter> 
           Mobo: Dell model: 0HNGW4 serial: <filter> UEFI: Dell v: A16 date: 12/05/2013 
Battery:   ID-1: BAT0 charge: 39.6 Wh condition: 39.6/48.8 Wh (81%) model: Samsung SDI DELL PT43699 status: Full 
CPU:       Topology: Dual Core model: Intel Core i5 M 560 bits: 64 type: MT MCP arch: Nehalem rev: 5 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21291 
           Speed: 1463 MHz min/max: 1199/2667 MHz Core speeds (MHz): 1: 1398 2: 1465 3: 1473 4: 1496 
Graphics:  Device-1: Intel Core Processor Integrated Graphics vendor: Dell Latitude E6410 driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.3 driver: intel unloaded: modesetting resolution: 1440x900~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 18.3.1 direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio vendor: Dell Latitude E6410 driver: snd_hda_intel 
           v: kernel bus ID: 00:1b.0 
           Sound Server: ALSA v: k4.20.1-1-MANJARO 
Network:   Device-1: Intel 82577LM Gigabit Network vendor: Dell Latitude E6410 driver: e1000e v: 3.2.6-k port: 7040 
           bus ID: 00:19.0 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Broadcom and subsidiaries BCM43224 802.11a/b/g/n vendor: Dell Wireless 1520 Half-size Mini PCIe Card 
           driver: wl v: kernel port: 7000 bus ID: 02:00.0 
           IF: wlp2s0 state: down mac: <filter> 
Drives:    Local Storage: total: 1.20 TiB used: 154.12 GiB (12.5%) 
           ID-1: /dev/sda vendor: Seagate model: ST9320423AS size: 298.09 GiB 
           ID-2: /dev/sdb type: USB vendor: Seagate model: Expansion size: 931.51 GiB 
Partition: ID-1: / size: 284.06 GiB used: 12.01 GiB (4.2%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 622.48 GiB used: 97.55 GiB (15.7%) fs: ext4 dev: /dev/sdb1 
           ID-3: swap-1 size: 8.18 GiB used: 823.5 MiB (9.8%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A sodimm: 42.0 C 
           Fan Speeds (RPM): cpu: 2901 
Info:      Processes: 195 Uptime: 2h 29m Memory: 3.72 GiB used: 2.66 GiB (71.7%) Init: systemd Compilers: gcc: 8.2.1 
           Shell: bash v: 4.4.23 inxi: 3.0.28
[jray@jr-dl rust-rocksdb]$ rustc -V
rustc 1.32.0 (9fda7c223 2019-01-16)
```
Moved from https://github.com/paritytech/shasper/issues/48.

**Comment by jwasinger** [comment]
you do have clang/llvm installed on your system right?

**Comment by jamesray1** [comment]
I have GCC, not sure about llvm, I will double check.

**Comment by aleksuss** [comment]
@jamesray1 What is you OS by the way ?

**Comment by jamesray1** [comment]
@aleksuss

> `System:    Host: jr-dl Kernel: 4.20.1-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: N/A Distro: Manjaro Linux `

**Comment by jamesray1** [comment]
I am installing `llvm-svn` with `yay llvm-svn`.

**Comment by aleksuss** [comment]
@jamesray1 did it help ?

**Comment by jamesray1** [comment]
@aleksuss, still building at 9%, I'll leave it on overnight. (About an hour ago I turned the computer off for the day by habit, forgetting that it was running. I booted up again and ran it.)

![](https://i.imgur.com/mfr5CyG.png)

**Comment by jamesray1** [comment]
So I have extra/llvm-libs installed, but not extra/llvm and extra/clang, nor extra//lld (Linked). Do I need any of these if I already have gcc?

**Comment by jamesray1** [comment]
While #259 helps to avoid this issue, ideally as part of compiling this crate it should check if clang is not installed and prompt the user to install it if not installed, then if yes install it automatically with a build script that checks the OS/distro and installs accordingly, otherwise abort.

**Comment by TomaszWaszczyk** [comment]
For me on Linux Mint helped:

`sudo apt-get install clang`
