### ISSUE TITLE
Any chance to make it work on iOS and Android?

### ISSUE THREAD

**Issue by lming** [rust-rocksdb/rust-rocksdb#324]
Hello,

I am trying to use rocksdb in a library shared across iOS and Android. However I got following errors. Anyone succeeded to use it on mobile?

For iOS, it stopped here:
https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L38

```
$ RUST_BACKTRACE=1 cargo build --target aarch64-apple-ios

   Compiling librocksdb-sys v6.1.2
error: failed to run custom build command for `librocksdb-sys v6.1.2`

Caused by:
  process didn't exit successfully: `/Users/ming/work/rust-ios-example/rust/target/debug/build/librocksdb-sys-ced30dc40e9a9c65/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'libclang error; possible causes include:
- Invalid flag syntax
- Unrecognized flags
- Invalid flag arguments
- File I/O errors
If you encounter an error missing from this list, please file an issue or a PR!', src/libcore/option.rs:1034:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1034
  11: core::option::Option<T>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:314
  12: bindgen::ir::context::BindgenContext::new
             at /Users/ming/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/ir/context.rs:559
  13: bindgen::Bindings::generate
             at /Users/ming/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1812
  14: bindgen::Builder::generate
             at /Users/ming/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.49.2/src/lib.rs:1208
  15: build_script_build::bindgen_rocksdb
             at ./build.rs:34
  16: build_script_build::main
             at ./build.rs:302
  17: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  21: std::panicking::try
             at src/libstd/panicking.rs:275
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  24: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  25: build_script_build::main
```

When I tried to build for Android there is a different error:

```
$ cargo build --target aarch64-linux-android

   Compiling librocksdb-sys v6.1.2
error: failed to run custom build command for `librocksdb-sys v6.1.2`

Caused by:
  process didn't exit successfully: `/Users/ming/work/rust-ios-example/rust/target/debug/build/librocksdb-sys-ced30dc40e9a9c65/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
NUM_JOBS = Some("4")
TARGET = Some("aarch64-linux-android")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CXX_aarch64-linux-android = None
CXX_aarch64_linux_android = None
TARGET_CXX = None
CXX = None
CXXFLAGS_aarch64-linux-android = None
CXXFLAGS_aarch64_linux_android = None
TARGET_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/table/get_context.o" "-c" "rocksdb/table/get_context.cc"
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/db/write_batch_base.o" "-c" "rocksdb/db/write_batch_base.cc"
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/db/event_helpers.o" "-c" "rocksdb/db/event_helpers.cc"
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/cache/clock_cache.o" "-c" "rocksdb/cache/clock_cache.cc"
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
exit code: 0
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/db/write_controller.o" "-c" "rocksdb/db/write_controller.cc"
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
exit code: 0
cargo:warning=In file included from rocksdb/table/get_context.cc:6:
cargo:warning=In file included from rocksdb/table/get_context.h:8:
cargo:warning=In file included from rocksdb/db/merge_context.h:9:
cargo:warning=In file included from rocksdb/db/dbformat.h:14:
cargo:warning=In file included from rocksdb/monitoring/perf_context_imp.h:7:
cargo:warning=In file included from rocksdb/monitoring/perf_step_timer.h:7:
cargo:warning=In file included from rocksdb/monitoring/perf_level_imp.h:8:
cargo:warning=In file included from rocksdb/port/port.h:18:
cargo:warning=rocksdb/port/port_posix.h:26:12: fatal error: 'machine/endian.h' file not found
cargo:warning=  #include <machine/endian.h>
cargo:warning=           ^~~~~~~~~~~~~~~~~~
running: "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/cache/lru_cache.o" "-c" "rocksdb/cache/lru_cache.cc"
cargo:warning=clang++: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
cargo:warning=clang++: warning: argument unused during compilation: '-mpclmul' [-Wunused-command-line-argument]
cargo:warning=1 error generated.
exit code: 1
cargo:warning=In file included from rocksdb/db/event_helpers.cc:6:
cargo:warning=In file included from rocksdb/db/event_helpers.h:11:
cargo:warning=In file included from rocksdb/db/column_family.h:17:
cargo:warning=In file included from rocksdb/db/memtable_list.h:15:
cargo:warning=In file included from rocksdb/db/dbformat.h:14:
cargo:warning=In file included from rocksdb/monitoring/perf_context_imp.h:7:
cargo:warning=In file included from rocksdb/monitoring/perf_step_timer.h:7:
cargo:warning=In file included from rocksdb/monitoring/perf_level_imp.h:8:
cargo:warning=In file included from rocksdb/port/port.h:18:
cargo:warning=rocksdb/port/port_posix.h:26:12: fatal error: 'machine/endian.h' file not found
cargo:warning=  #include <machine/endian.h>
cargo:warning=           ^~~~~~~~~~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1
cargo:warning=In file included from rocksdb/cache/lru_cache.cc:14:
cargo:warning=In file included from rocksdb/cache/lru_cache.h:13:
cargo:warning=In file included from rocksdb/cache/sharded_cache.h:15:
cargo:warning=In file included from rocksdb/port/port.h:18:
cargo:warning=rocksdb/port/port_posix.h:26:12: fatal error: 'machine/endian.h' file not found
cargo:warning=  #include <machine/endian.h>
cargo:warning=           ^~~~~~~~~~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1
exit code: 0

--- stderr


error occurred: Command "aarch64-linux-android-clang++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ming/work/rust-ios-example/rust/target/aarch64-linux-android/debug/build/librocksdb-sys-7c11213694770479/out/rocksdb/table/get_context.o" "-c" "rocksdb/table/get_context.cc" with args "aarch64-linux-android-clang++" did not execute successfully (status code exit code: 1).

```

**Comment by dvdplm** [comment]
For android there was [this](https://github.com/rust-rocksdb/rust-rocksdb/pull/343) that was merged recently. Does that help?

**Comment by vimmerru** [comment]
I was able to compile it for android with NDK 21 using the following command

```
PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH CXX="armv7a-linux-androideabi21-clang++"  BINDGEN_EXTRA_CLANG_ARGS="--target=armv7-linux-androideabi" cargo build --target armv7-linux
```

and specification of path to ar and linker in .cargo/config

```
[target.armv7-linux-androideabi]
ar = "/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar"
linker = "/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang"
```

**Comment by vimmerru** [comment]
Unfortunately build only works for armv7 and aarch64 targets and breaks on i686 and x86_64 targets that are definitely required (to use on Android EMU for example). The error looks like

```
cargo:warning=rocksdb/util/crc32c.cc:667:21: error: '__builtin_ia32_pclmulqdq128' needs target feature pclmul
cargo:warning=  const auto res0 = _mm_clmulepi64_si128(crc0_xmm, multiplier, 0x00);
cargo:warning=                    ^
cargo:warning=/usr/local/Caskroom/android-ndk/21/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/__wmmintrin_pclmul.h:45:13: note: expanded from macro '_mm_clmulepi64_si128'
cargo:warning=  ((__m128i)__builtin_ia32_pclmulqdq128((__v2di)(__m128i)(X), \
cargo:warning=            ^
cargo:warning=rocksdb/util/crc32c.cc:669:21: error: '__builtin_ia32_pclmulqdq128' needs target feature pclmul
cargo:warning=  const auto res1 = _mm_clmulepi64_si128(crc1_xmm, multiplier, 0x10);
cargo:warning=                    ^
cargo:warning=/usr/local/Caskroom/android-ndk/21/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/include/__wmmintrin_pclmul.h:45:13: note: expanded from macro '_mm_clmulepi64_si128'
cargo:warning=  ((__m128i)__builtin_ia32_pclmulqdq128((__v2di)(__m128i)(X), \
cargo:warning=            ^
cargo:warning=2 errors generated.
```

For x86_64-androdi So seems the problem in setting of unsupported pclmul for ```x86_64``` target in this block

```
  if target.contains("x86_64") {
        // This is needed to enable hardware CRC32C. Technically, SSE 4.2 is
        // only available since Intel Nehalem (about 2010) and AMD Bulldozer
        // (about 2011).
        config.define("HAVE_PCLMUL", Some("1"));
        config.define("HAVE_SSE42", Some("1"));
        config.flag_if_supported("-msse2");
        config.flag_if_supported("-msse4.1");
        config.flag_if_supported("-msse4.2");
        config.flag_if_supported("-mpclmul");
    }
```

i was able to fix build by changing it to 

```
 if target.contains("x86_64") && !target.contains("android") {
        // This is needed to enable hardware CRC32C. Technically, SSE 4.2 is
        // only available since Intel Nehalem (about 2010) and AMD Bulldozer
        // (about 2011).
        config.define("HAVE_PCLMUL", Some("1"));
        config.define("HAVE_SSE42", Some("1"));
        config.flag_if_supported("-msse2");
        config.flag_if_supported("-msse4.1");
        config.flag_if_supported("-msse4.2");
        config.flag_if_supported("-mpclmul");
    }
```

Need to check for SSE42 support status here. Maybe we can avoid mpclmul only.

**Comment by vimmerru** [comment]
For i686 seems it works on current master

**Comment by vimmerru** [comment]
Here is the fix https://github.com/rust-rocksdb/rust-rocksdb/pull/429

**Comment by vimmerru** [comment]
Also build doesn't work without ```BINDGEN_EXTRA_CLANG_ARGS="--target=aarch64-linux-android" ``` that confuses a lot. 

The problem is current versions of bindgen don't provide correct target for invoked clang during cross-compilation.  Here is workaround to set BINDGEN_EXTRA_CLANG_ARGS variable and provide target here. For example, BINDGEN_EXTRA_CLANG_ARGS="--target=aarch64-linux-android", but it is hard to get this information without communication with bindgen developers.

As an option we can explicitly set target for bindgen.
