### ISSUE TITLE
failed to run custom build command

### ISSUE THREAD

**Issue by Arnaz87** [rust-rocksdb/rust-rocksdb#355]
```
error: failed to run custom build command for `librocksdb-sys v6.2.4 (/home/arnaud/panteum/rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/home/arnaud/panteum/rocksdb/target/debug/build/librocksdb-sys-f82367b6f79a7a9a/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
The `rocksdb` directory is empty, did you forget to pull the submodules?
Try `git submodule update --init --recursive`

--- stderr
thread 'main' panicked at 'explicit panic', librocksdb-sys/build.rs:29:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/panicking.rs:400
  12: build_script_build::fail_on_empty_directory
             at librocksdb-sys/build.rs:29
  13: build_script_build::main
             at librocksdb-sys/build.rs:309
  14: std::rt::lang_start::{{closure}}
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  18: std::panicking::try
             at src/libstd/panicking.rs:265
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:395
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  21: std::rt::lang_start
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  22: main
  23: __libc_start_main
  24: _start
```

```
$ rustc --version      
> rustc 1.41.0-nightly (412f43ac5 2019-11-24)
```

**Comment by Arnaz87** [comment]
The fix is in the same error message, I forgot to update the submodules
