### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v5.18.3` Windows

### ISSUE THREAD

**Issue by L-KH** [rust-rocksdb/rust-rocksdb#382]
Compiling librocksdb-sys v5.18.3
   Compiling cennznet v0.9.25-beta (C:\Users\charingane\Desktop\cennznet-master)
error: failed to run custom build command for `librocksdb-sys v5.18.3`

Caused by:
  process didn't exit successfully: `C:\Users\charingane\Desktop\cennznet-master\target\debug\build\librocksdb-sys-b28aaa0ace6f4e98\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [(C:\\Program Files\\LLVM\\bin\\libclang.dll: invalid DLL (64-bit))])"', src\libcore\result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
![image](https://user-images.githubusercontent.com/12660772/72892545-11c6ba00-3d17-11ea-9973-647cba173bf8.png)
Please how to fix.

**Comment by vitvakatu** [comment]
Hello, thank you for creating an issue. Are you depending on a particular rocksdb version? 
Latest librocksdb-sys version is `6.2.4`, with `rocksdb` version `0.13.0`. It has the same problem though, I'm asking if we need to back-port the fix to the `5.18.3`

This issue is a dublicate of #381

**Comment by TomaszWaszczyk** [comment]
I have similar issue with newer version of `librocksdb-sys v0.8.0+7.4.4`:

```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/home/tomek/ssd/workspaces/polkadot/target/debug/build/librocksdb-sys-ef257bddcda54e79/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /home/tomek/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/fallback.rs:730:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Hasnayeen** [comment]
I'm having a similar issue on ubuntu 22.04
```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/mnt/work/projects/rust/larks/target/debug/build/librocksdb-sys-4f51bde46f377b21/build-script-build` (exit status: 1)
```

**Comment by aniketfuryrocks** [comment]
I am still encountering this problem while compiling solana on open suse tumbleweed wsl. Any one found any fixes ?

**Comment by kevin-valerio** [comment]
Same problem here...

**Comment by L-KH** [comment]
One possible solution is to install the libclang library and add its location to the LIBCLANG_PATH environment variable. You can try installing LLVM on your system and adding its bin directory to your system's PATH environment variable.

Alternatively, you can try specifying the location of the libclang library by setting the LIBCLANG_PATH environment variable to the path where it is installed. For example, you can try running the following command before building the project:

`set LIBCLANG_PATH=C:\path\to\libclang.dll`

Replace C:\path\to\libclang.dll with the actual path to the library on your system.

If the issue persists, you can try updating your Rust and LLVM installations to the latest versions and try building the project again. You can also check if there are any updates available for the Cennznet project or its dependencies that address this issue.

I hope this helps!

**Comment by tatulea** [comment]
On linux you can do `LIBCLANG_PATH=/usr/lib/llvm-10/lib cargo build`

**Comment by devlancer412** [comment]
Also have same error on windows. Are there any solution?

**Comment by sam0x17** [comment]
> I have similar issue with newer version of `librocksdb-sys v0.8.0+7.4.4`:
> 
> ```
> error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`
> 
> Caused by:
>   process didn't exit successfully: `/home/tomek/ssd/workspaces/polkadot/target/debug/build/librocksdb-sys-ef257bddcda54e79/build-script-build` (exit status: 101)
>   --- stderr
>   thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /home/tomek/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/fallback.rs:730:9
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

this should really be pulled out into its own issue

**Comment by mina86** [comment]
Any news on this? I’ve tried ` LIBCLANG_PATH=/usr/lib/llvm-16/lib ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu cargo build` but to no avail:

```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/home/mpn/code/comp/tinydancer/target/debug/build/librocksdb-sys-e72a69a29b0df971/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/mpn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.51/src/fallback.rs:752:9:
  "enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident
```

```
$ cargo tree |grep rocksdb
├── rocksdb v0.19.0
│   └── librocksdb-sys v0.8.0+7.4.4
│   │   │   │   ├── rocksdb v0.19.0 (*)
$ dpkg -l |grep -e libclang -e rocksdb
ii  libclang-16-dev           1:16.0.6-27
ii  libclang-common-16-dev    1:16.0.6-27
ii  libclang-dev              1:16.0-58.1
ii  libclang-rt-16-dev:amd64  1:16.0.6-27
ii  libclang1-16t64           1:16.0.6-27
ii  librocksdb-dev            9.2.1-3
ii  librocksdb9.2             9.2.1-3
```

**Comment by lakefishingman522** [comment]
I have similar error. When I tried```cargo build --release```, I got this error.
```
Caused by:
  process didn't exit successfully: `/opt/atlassian/pipelines/agent/build/target/release/build/librocksdb-sys-29519c67ad8e6923/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['[libclang.so](http://libclang.so/)', 'libclang-*.so', '[libclang.so](http://libclang.so/).*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
