### ISSUE TITLE
Failed compiling rocksdb on win10

### ISSUE THREAD

**Issue by GuyTabak** [rust-rocksdb/rust-rocksdb#476]
Running `C:\Users\Guy\Workspace\dev\rocks2\rust-rocksdb\target\debug\build\librocksdb-sys-7792c8b6a17adb0e\build-script-build`
[librocksdb-sys 6.11.4] error: header 'rocksdb/include/rocksdb/c.h' does not exist.
[librocksdb-sys 6.11.4] thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys\build.rs:44:10
[librocksdb-sys 6.11.4] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `librocksdb-sys v6.11.4 (C:\Users\Guy\Workspace\dev\rocks2\rust-rocksdb\librocksdb-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\Guy\Workspace\dev\rocks2\rust-rocksdb\target\debug\build\librocksdb-sys-7792c8b6a17adb0e\build-script-build` (exit code: 101)
  --- stderr
  error: header 'rocksdb/include/rocksdb/c.h' does not exist.
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys\build.rs:44:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Using the following release: https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.15.0

I have Clang and LLVM installed on my pc, building works fine on mac.

**Comment by GuyTabak** [comment]
Was missing visual studio build tools 2017
