### ISSUE TITLE
cargo build fails on M1 Silicon

### ISSUE THREAD

**Issue by fgadaleta** [rust-rocksdb/rust-rocksdb#504]
```

   Compiling librocksdb-sys v6.17.3 (/Users/frag/c0ding/rust-rocksdb/librocksdb-sys)
error: failed to run custom build command for `librocksdb-sys v6.17.3 (/Users/frag/c0ding/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/Users/frag/c0ding/rust-rocksdb/target/debug/build/librocksdb-sys-5a821b03411c25b9/build-script-build` (exit code: 101)
  --- stderr
  error: header 'rocksdb/include/rocksdb/c.h' does not exist.
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys/build.rs:44:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(dev) frag@buddha ~/c0ding/rust-rocksdb % RUST_BACKTRACE=1 cargo build
   Compiling librocksdb-sys v6.17.3 (/Users/frag/c0ding/rust-rocksdb/librocksdb-sys)
error: failed to run custom build command for `librocksdb-sys v6.17.3 (/Users/frag/c0ding/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/Users/frag/c0ding/rust-rocksdb/target/debug/build/librocksdb-sys-5a821b03411c25b9/build-script-build` (exit code: 101)
  --- stderr
  error: header 'rocksdb/include/rocksdb/c.h' does not exist.
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys/build.rs:44:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/core/src/option.rs:1300:5
     3: core::result::Result<T,E>::expect
               at /Users/frag/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:997:23
     4: build_script_build::bindgen_rocksdb
               at ./build.rs:37:20
     5: build_script_build::main
               at ./build.rs:346:5
     6: core::ops::function::FnOnce::call_once
               at /Users/frag/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  
  ```

**Comment by fgadaleta** [comment]
forgot to `git submodule update --init --recursive`
