### ISSUE TITLE
Github Actions cross-platform complie error!

### ISSUE THREAD

**Issue by RustChater** [rust-rocksdb/rust-rocksdb#598]
test.yaml 
```
name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - build: aarch64
          os: ubuntu-latest
          rust: stable
          target: aarch64-unknown-linux-gnu
          linker: gcc-aarch64-linux-gnu
          cross: true
   
    steps:
    - name: Install Linker
      run: |
        sudo apt update
        sudo apt install -y ${{ matrix.linker }}     
    - name: Install Rust
      run: rustup install ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt install -y llvm clang
        rustup target add ${{ matrix.target }}
        cargo build --release --target ${{ matrix.target }}
```

got error:

```
error: failed to run custom build command for `librocksdb-sys v6.20.3`

Caused by:
  process didn't exit successfully: `/home/runner/work/rustchat-server/rustchat-server/target/release/build/librocksdb-sys-383bfd4247f60f39/build-script-build` (exit status: 101)
  --- stderr
  /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
  /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found, err: true
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', /home/runner/.cargo/registry/src/librocksdb-sys-6.20.3/build.rs:44:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 101.
```

**Comment by Dirreke** [comment]
stdarg.h包含错了

**Comment by timmyjose** [comment]
> test.yaml
> 
> ```
> name: Test
> on:
>   push:
>     branches: [ main ]
>   pull_request:
>     branches: [ main ]
> 
> jobs:
>   build:
>     runs-on: ${{ matrix.os }}
>     strategy:
>       matrix:
>         include:
>         - build: aarch64
>           os: ubuntu-latest
>           rust: stable
>           target: aarch64-unknown-linux-gnu
>           linker: gcc-aarch64-linux-gnu
>           cross: true
>    
>     steps:
>     - name: Install Linker
>       run: |
>         sudo apt update
>         sudo apt install -y ${{ matrix.linker }}     
>     - name: Install Rust
>       run: rustup install ${{ matrix.rust }}
>     - uses: actions/checkout@v2
>     - name: Build
>       run: |
>         sudo apt install -y llvm clang
>         rustup target add ${{ matrix.target }}
>         cargo build --release --target ${{ matrix.target }}
> ```
> 
> got error:
> 
> ```
> error: failed to run custom build command for `librocksdb-sys v6.20.3`
> 
> Caused by:
>   process didn't exit successfully: `/home/runner/work/rustchat-server/rustchat-server/target/release/build/librocksdb-sys-383bfd4247f60f39/build-script-build` (exit status: 101)
>   --- stderr
>   /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
>   /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found, err: true
>   thread 'main' panicked at 'unable to generate rocksdb bindings: ()', /home/runner/.cargo/registry/src/librocksdb-sys-6.20.3/build.rs:44:10
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> Error: Process completed with exit code 101.
> ```

I'm seeing a similar error. Did you resolve that?

**Comment by timmyjose** [comment]
@Dirreke Thank you for your response! It is useful as a starting point for me.

I am not very familiar with C++'s ecosystem, but here is my exact usecase (in brief). I would be very grateful if you have any insights on it, but wouldn't expect too much. 🙏 

So I'm trying to cross-compile a Rust crate which has `rockdsb` as a dependency for Android targets. So, for instance, I run it using `cargo ndk` like so (after having installed the target platform, `aarch64-linxu-android`):

```
 cargo ndk --target aarch64-linux-android --platform 21 -- build --release
```

On my laptop (Apple ARM64), it cross-compiles with no issues. However, in my build environment (using an external service, where the build platform is `Ubuntu 22.04`, `X86_64`), I get the __exact__ error message that you do. 

Do you have an idea as to how I could use `BINDGEN_EXTRA_CLANG_ARGS​ = ​"​--sysroot ${TOOLCHAIN_PATH}＂` in this context? 

Again, thank you so much for your help. It's been difficult finding the exact error with a context similar enough to mine!

**Comment by timmyjose** [comment]
@Dirreke Thank you again for the help, Dirreke. I had in fact tried that very same command after reading the `cargo ndk` docs again 😄. Unfortunately, that env is set *after* the `cargo ndk` is run. 

> f not, you can try to change ${CARGO_NDK_SYSROOT_PATH} to the right path which should have the subdirectory like ${CARGO_NDK_SYSROOT_PATH} /usr/, ${CARGO_NDK_SYSROOT_PATH}/lib/...

I'll attempt following this route and see. 👍

**Comment by timmyjose** [comment]
> I forgot to type the `--sysroot`. It should be `BINDGEN_EXTRA_CLANG_ARGS​ = ​"​--sysroot ${TOOLCHAIN_PATH}＂`

Yes, the command I'd tried was this, including the `--sysroot`:

```
BINDGEN_EXTRA_CLANG_ARGS="--sysroot ${CARGO_NDK_SYSROOT_PATH}"  cargo ndk --target aarch64-linux-android --platform 21 -- -vv build --release
```

**Comment by timmyjose** [comment]
@Dirreke Your suggestions led to the build working successfully! 😄 

```
    SYSROOT_PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
    BINDGEN_EXTRA_CLANG_ARGS="--sysroot ${SYSROOT_PATH}" cargo ndk --bindgen --target aarch64-linux-android --platform 21 -- build --release
```

worked. Thank you so much! 🙏
