### ISSUE TITLE
Having issue building on Debian Sid

### ISSUE THREAD

**Issue by Brando753** [rust-rocksdb/rust-rocksdb#713]
Everytime I try to build a Rust project that uses rocksdb I get the same build errors:

```
   Compiling librocksdb-sys v0.8.0+7.4.4
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/home/brandon/sandbox/project/target/debug/build/librocksdb-sys-9c58c99f52a8c5ef/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

First identified when trying to build substrate and posted here https://substrate.stackexchange.com/questions/6088/unable-to-compile-substrate-template-error-failed-to-run-custom-build-command

I do have clang and llvm installed. I have even compiled clang + llvm from sources and installed them on the computer in an attempt to make sure the build system should work. I have the librocksdb-dev package installed as well. I am running on Debian Sid. I have entirely uninstalled librocksdb-dev llvm clang and even rust and then reinstalled them. I am unsure how to continue.  

The output of `rustup +nightly show`:

```
➜  ~ rustup +nightly show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/brandon/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.67.0-nightly (c97b539e4 2022-11-30)

```

**Comment by aleksuss** [comment]
Could you expose a backtrace?

**Comment by aleksuss** [comment]
It seems error is related to Linux because I've just tried to compile it on my host (macOS, arm64). Everything compiled fine.

**Comment by m-yahya** [comment]
Thank you for the response.
Any idea what could be helpful in the current case?
I have already tried removing broken packages.

**Comment by aleksuss** [comment]
@m-yahya could you try to build `rocksdb` only?
```shell
git clone https://github.com/rust-rocksdb/rust-rocksdb
cd rust-rocksdb
cargo +nightly build -r
```

**Comment by m-yahya** [comment]
no luck!

```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4 (/home/yahya/Documents/GitHub/integritee/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/rust-rocksdb/target/release/build/librocksdb-sys-640f29d7c8211b9f/build-script-build` (exit status: 101)
  --- stdout
  Running command: "git submodule update --init" in dir: ../
  Submodule path 'librocksdb-sys/rocksdb': checked out 'e656fa3d196c5b4c8a77255db1e6cd36a7ded348'
  Submodule path 'librocksdb-sys/snappy': checked out '2b63814b15a2aaae54b7943f0cd935892fae628f'

  --- stderr
  Cloning into '/rust-rocksdb/librocksdb-sys/rocksdb'...
  Cloning into '/rust-rocksdb/librocksdb-sys/snappy'...
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With backtrace:

```
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4 (/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/rust-rocksdb/target/release/build/librocksdb-sys-640f29d7c8211b9f/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident', /.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/e0098a5cc3a87d857e597af824d0ce1ed1ad85e0/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/e0098a5cc3a87d857e597af824d0ce1ed1ad85e0/library/core/src/panicking.rs:65:14
     2: proc_macro2::fallback::validate_ident
     3: proc_macro2::fallback::Ident::_new
     4: proc_macro2::fallback::Ident::new
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
     8: bindgen::ir::context::BindgenContext::rust_ident
     9: <bindgen::ir::enum_ty::Enum as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    13: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    15: bindgen::codegen::codegen::{{closure}}
    16: bindgen::ir::context::BindgenContext::gen
    17: bindgen::codegen::codegen
    18: bindgen::Bindings::generate
    19: bindgen::Builder::generate
    20: build_script_build::bindgen_rocksdb
    21: build_script_build::main
    22: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by aleksuss** [comment]
Try to bump `bindgen` version to 0.63.0 [here](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/Cargo.toml#L40) and try again to build rocksdb please.

**Comment by m-yahya** [comment]
Thank you for the guidance. I could compile with the following warnings:
```
Compiling librocksdb-sys v0.8.0+7.4.4 (/rust-rocksdb/librocksdb-sys)
warning: In file included from /usr/include/x86_64-linux-gnu/c++/12/bits/c++allocator.h:33,
warning:                  from /usr/include/c++/12/bits/allocator.h:46,
warning:                  from /usr/include/c++/12/memory:64,
warning:                  from rocksdb/trace_replay/trace_replay.h:9,
warning:                  from rocksdb/trace_replay/trace_replay.cc:6:
warning: In member function ‘void std::__new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = unsigned int; _Args = {const unsigned int&}; _Tp = unsigned int]’,
warning:     inlined from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = unsigned int; _Args = {const unsigned int&}; _Tp = unsigned int]’ at /usr/include/c++/12/bits/alloc_traits.h:516:17,
warning:     inlined from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>]’ at /usr/include/c++/12/bits/stl_vector.h:1281:30,
warning:     inlined from ‘static rocksdb::Status rocksdb::TracerHelper::DecodeTraceRecord(rocksdb::Trace*, int, std::unique_ptr<rocksdb::TraceRecord>*)’ at rocksdb/trace_replay/trace_replay.cc:324:25:
warning: /usr/include/c++/12/bits/new_allocator.h:175:11: warning: ‘tmp_cfid’ may be used uninitialized [-Wmaybe-uninitialized]
warning:   175 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
warning:       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: rocksdb/trace_replay/trace_replay.cc: In static member function ‘static rocksdb::Status rocksdb::TracerHelper::DecodeTraceRecord(rocksdb::Trace*, int, std::unique_ptr<rocksdb::TraceRecord>*)’:
warning: rocksdb/trace_replay/trace_replay.cc:320:18: note: ‘tmp_cfid’ declared here
warning:   320 |         uint32_t tmp_cfid;
warning:       |                  ^~~~~~~~
   Compiling rocksdb v0.19.0 (/rust-rocksdb)
    Finished release [optimized] target(s) in 3m 09s
  ```

**Comment by m-yahya** [comment]
I'm still having the same error with compiling the `substrate-node-template`.
Any guidance on how to apply this patch to fix the other compiling issue, please?

**Comment by aleksuss** [comment]
If `substrate-node-template` has `rocksdb` as a direct dependency then you can create a fork of the `rocksdb` and apply this patch and use this fork. But if the dependency is transitive, you need to wait for the release of the patched version of the `rocksdb`.

**Comment by m-yahya** [comment]
I couldn't solve the issue. 
However, I could solve the issue with a clean OS reset.

**Comment by ganesh1233456** [comment]
`brew install openssl cmake llvm` I solved this issue by running this command in terminal.

**Comment by krhougs** [comment]
I met this on macOS(arm64) with llvm 16 and resolved it by downgrading llvm to 15.

**Comment by simbahebinbo** [comment]
I met this on macOS(arm64) with llvm 16 and resolved it by downgrading llvm to 15.

firstly, install brew in m1 chip 

$ sudo mkdir -p /opt/homebrew
$ sudo chown -R $(whoami) /opt/homebrew 
$ cd /opt
$ curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
$ echo 'export PATH="/opt/homebrew/bin:${PATH}"' >> ~/.zshrc
$ echo 'alias abrew="arch -arm64 /opt/homebrew/bin/brew"' >> ~/.zshrc
$ echo 'alias ibrew="arch -x86_64 /usr/local/bin/brew"' >> ~/.zshrc

secondly, install llvm 
$ abrew install llvm@15
$ echo 'export PATH="/opt/homebrew/opt/llvm@15/bin:$PATH"' >> ~/.zshrc
$ echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm@15/lib"' >> ~/.zshrc
$ echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm@15/include"' >> ~/.zshrc


thirdly,  update cache 
$ cargo clean
$ cargo update
$ rustup update

finally
$ cargo build

**Comment by Brando753** [comment]
I can confirm on Linux this issue no longer is occurring for me, so I am going to mark it closed.

**Comment by ameba23** [comment]
> For me, downgrading gcc from 13 to 12 solved the issue. Running clang 15.0.7 on Arch.

Thanks for that - this worked for me too.

**Comment by esemeniuc** [comment]
Yea you can do `sudo pacman -U https://archive.archlinux.org/packages/g/gcc/gcc-12.2.1-4-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-12.2.1-4-x86_64.pkg.tar.zst`
