### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`

### ISSUE THREAD

**Issue by revoltez** [rust-rocksdb/rust-rocksdb#768]
i have a project that is dependant on that specific version of librocksdb-sys and wheni run `cargo build --release` it show the following 

```
error:failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`
Caused by:
  process didn't exit successfully: `/home/ezio/projects/testhex/target/debug/build/librocksdb-sys-2c05e423d101bec2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_860_1)" is not a valid Ident', /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:811:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
     2: proc_macro2::fallback::validate_ident
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:811:9
     3: proc_macro2::fallback::Ident::_new
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:753:9
     4: proc_macro2::fallback::Ident::new
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:763:9
     5: proc_macro2::Ident::new
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/lib.rs:972:21
     6: bindgen::ir::context::BindgenContext::rust_ident_raw
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/ir/context.rs:878:9
     7: bindgen::ir::context::BindgenContext::rust_ident
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/ir/context.rs:870:9
     8: <bindgen::ir::enum_ty::Enum as bindgen::codegen::CodeGenerator>::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:2907:21
     9: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:1004:39
    10: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:492:17
    11: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:515:21
    12: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:545:13
    13: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:483:17
    14: bindgen::codegen::codegen::{{closure}}
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:4287:9
    15: bindgen::ir::context::BindgenContext::gen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/ir/context.rs:1190:19
    16: bindgen::codegen::codegen
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/codegen/mod.rs:4251:5
    17: bindgen::Bindings::generate
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2374:32
    18: bindgen::Builder::generate
               at /home/ezio/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:1478:9
    19: build_script_build::bindgen_rocksdb
               at ./build.rs:36:20
    20: build_script_build::main
               at ./build.rs:325:5
    21: core::ops::function::FnOnce::call_once
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
i tried runing adding the same on an empty project with `cargo add librocksdb-sys@0.6.1+6.28.2` and the same error appears

environment:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ezio/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2022-11-11-x86_64-unknown-linux-gnu
nightly-2022-11-30-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.63.0-x86_64-unknown-linux-gnu
1.68.2-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.68.2 (9eb3afe9e 2023-03-27)
```
OS: opensuse tumbleweed (latest update)

**Comment by im-0** [comment]
Probably caused by this: https://github.com/rust-lang/rust-bindgen/issues/2488 / https://github.com/rust-lang/rust-bindgen/issues/2312

**Comment by revoltez** [comment]
@im-0  its a clang and llvm version dependancy issue, i distro hopped to pop!_os and it compiles just fine.

**Comment by aleksuss** [comment]
@im-0 is right. The issue is related to a bug in the `rust-bindgen`. I released `librocksdb-sys v0.6.2+6.28.2` with `rust-bindgen` 0.65. Try it now.

**Comment by revoltez** [comment]
@aleksuss i wonder why it worked when i distro hopped!

**Comment by aleksuss** [comment]
@revoltez do you have pre-installed `rocksdb`?

**Comment by revoltez** [comment]
@aleksuss  nope, i ran cargo clean and even removed ~/.cargo just to be sure and it didn't work

**Comment by im-0** [comment]
> @aleksuss i wonder why it worked when i distro hopped!

Older Clang? It seems that this problem appear only with LLVM/Clang 16 that was released just a month ago or so.

**Comment by revoltez** [comment]
@im-0 yeah definitely, you should get it working with clang14

**Comment by mxtsns** [comment]
> I have similar error on Fedora 38.

i have the same problem. Did you solve that?

**Comment by kevindong** [comment]
I get a similar error on macOS with Apple Clang 15.x and RocksDb 7.x. The fix for me was to either:

* downgrade to Clang 14.x (if you're on macOS, downgrade your Xcode developer tools/Xcode in general to 14.x)
* upgrade the Rust `bindgen` dependency to >= `0.62`

**Comment by gruberb** [comment]
Any update on this? Happens on Arch and Fedora. Solution is (as of now) to downgrade to `gcc12`

**Comment by sam0x17** [comment]
I'm still getting this issue on arch even after downgrading to `gcc12`

**Comment by HudsonGraeme** [comment]
> I get a similar error on macOS with Apple Clang 15.x and RocksDb 7.x. The fix for me was to either:
> 
> * downgrade to Clang 14.x (if you're on macOS, downgrade your Xcode developer tools/Xcode in general to 14.x)
> * upgrade the Rust `bindgen` dependency to >= `0.62`

Thank you, this helped me out! I ran this before the compile I was trying to do, and it fixed the error.

```console
brew install llvm@14
export PATH="/opt/homebrew/opt/llvm@14/bin:$PATH" 
clang --version # Should return 14
```

**Comment by Kalanamith** [comment]
Im looking for a solution for this , happens with Polkadot Version 0.9.30

**Comment by sam0x17** [comment]
> Im looking for a solution for this , happens with Polkadot Version 0.9.30

have fun, our solution was upgrading to at least 1.0.0

**Comment by jamesmurphy0622** [comment]
error: failed to run custom build command for `librocksdb-sys v6.2.4`

Caused by:
  process didn't exit successfully: `E:\job\substrate-evm\substrate-evm\target\release\build\librocksdb-sys-eb28e95fde0524b0\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=rocksdb/
  cargo:rerun-if-changed=snappy/
  cargo:rerun-if-changed=lz4/
  cargo:rerun-if-changed=zstd/
  cargo:rerun-if-changed=zlib/
  cargo:rerun-if-changed=bzip2/
  cargo:warning=couldn't execute `llvm-config --prefix` (error: program not found)
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

  --- stderr
  thread 'main' panicked at C:\Users\Henry\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.49.4\src/lib.rs:1710:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"    
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `substrate-evm-runtime v2.0.0 (E:\job\substrate-evm\substrate-evm\runtime)`

Caused by:
  process didn't exit successfully: `E:\job\substrate-evm\substrate-evm\target\release\build\substrate-evm-runtime-82d7c0370596e30d\build-script-build` (exit code: 1)
  --- stdout
  Executing build command: "rustup" "run" "nightly-2024-01-22" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=E:\\job\\substrate-evm\\substrate-evm\\target\\release\\wbuild\\substrate-evm-runtime\\Cargo.toml" "--color=always" "--release"

  --- stderr

error[E0554]: `#![feature]` may not be used on the stable release channel
    --> C:\Users\Henry\.cargo\git\checkouts\substrate-7e08433d4c370a21\26a4b73\primitives\io\src\lib.rs:22:35
     |
  22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  For more information about this error, try `rustc --explain E0554`.
  error: could not compile `sp-io` (lib) due to 1 previous error
  warning: build failed, waiting for other jobs to finish...

**Comment by Raj-RR1** [comment]
What is the actual summary here? How do i fix this. I am getting this error on Ubuntu 24.04 LTS x64. Also i am on substrate release branch v0.9.25.

**Comment by matthew-mcallister** [comment]
I found that I'm only able to work around this on Debian by downgrading to a clang version <=15.

**Comment by coreggon11** [comment]
For M1 users, this did the trick for me (posted the answer the SO)

https://stackoverflow.com/a/79579733/6204881

**Comment by ppdouble** [comment]
> I have similar error on Fedora 38.

I execute ` dnf install clang` to remove this error for fedora 41.

**Comment by SengerM** [comment]
Getting this problem with `clang version 20.1.8 (Fedora 20.1.8-4.fc42)`. Solution from [here](https://github.com/facebook/rocksdb/issues/13365#issuecomment-2833978676):
```
export CXXFLAGS="$CXXFLAGS -include cstdint"
```
