### ISSUE TITLE
TransactionDB `open_default` panic

### ISSUE THREAD

**Issue by fansehep** [rust-rocksdb/rust-rocksdb#881]
This demo in my laptop, it will panic.
```Rust
use rocksdb::TransactionDB;

fn main() {
    let _db: TransactionDB = rocksdb::TransactionDB::open_default("./rocks_data").unwrap();
    
    println!("Hello, world!");
}
```
output:
```Rust
thread 'main' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3a36386dc1075018dc7ca2640a2656adb31a61fe/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/3a36386dc1075018dc7ca2640a2656adb31a61fe/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/3a36386dc1075018dc7ca2640a2656adb31a61fe/library/core/src/panicking.rs:120:5
   ...
```

I'm confused about this.

**Comment by fansehep** [comment]
I switch the rustc to stable, it will be ok. :(

**Comment by peacess** [comment]
i have the same case,  just call open_default,  and then panic

**Comment by ravlio** [comment]
Same, but only during tests (`#[cfg(test)]`)

**Comment by miladamery** [comment]
I Have the same issue.
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap

any idea why this happens?

**Comment by pragmaxim** [comment]
It only happens with 
```
rustc 1.78.0 (9b00956e5 2024-04-29)
```
but not 
```
rustc 1.75.0
```

```
        let mut opts = Options::default();
        opts.create_if_missing(true);
        let txn_db_opts = TransactionDBOptions::default();
        let db = TransactionDB::open(&opts, &txn_db_opts, db_path).unwrap();
```

```
   0: rust_begin_unwind                                                                                                                                                                                                                        
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5                                                                                                                                             
   1: core::panicking::panic_nounwind_fmt::runtime                                                                                                                                                                                             
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:110:18                                                                                                                                           
   2: core::panicking::panic_nounwind_fmt                                                                                                                                                                                                      
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:123:9                                                                                                                                            
   3: core::panicking::panic_nounwind                                                                                                                                                                                                          
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:156:5
   4: core::intrinsics::copy_nonoverlapping::precondition_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/intrinsics.rs:2799:21
   5: core::intrinsics::copy_nonoverlapping
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/intrinsics.rs:2969:5
   6: rocksdb::transactions::transaction_db::TransactionDB<T>::open_cf_descriptors_internal
             at /home/lisak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocksdb-0.22.0/src/transactions/transaction_db.rs:303:13
   7: rocksdb::transactions::transaction_db::TransactionDB<T>::open_cf
             at /home/lisak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocksdb-0.22.0/src/transactions/transaction_db.rs:200:9
   8: rocksdb::transactions::transaction_db::TransactionDB<T>::open
             at /home/lisak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocksdb-0.22.0/src/transactions/transaction_db.rs:179:9
   9: index_btc::merkle::AddressIndexer::new
```

**Comment by mpartel** [comment]
Workaround:
```
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "1cf906dc4087f06631820f13855e6b27bd21b972" }
```

The other commits between 0.22.0 and that one are very minor.

**Comment by peacess** [comment]
panic in 1.79.0

**Comment by zilong-dai** [comment]
release version may not panic

**Comment by zilong-dai** [comment]
This commit on master branch have fixed this issue https://github.com/rust-rocksdb/rust-rocksdb/commit/1cf906dc4087f06631820f13855e6b27bd21b972
