### ISSUE TITLE
fatal error: 'st dbool.h' file not found

### ISSUE THREAD

**Issue by SteveLauC** [rust-rocksdb/rust-rocksdb#903]
Hi, thanks for the project!

I tried to build the crate myself, then I ran into the following error:

```sh
error: failed to run custom build command for `librocksdb-sys v0.17.0+9.0.0 (rust-rocksdb/librocksdb-sys)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `rust-rocksdb/target/debug/build/librocksdb-sys-b946f8dd5be7bbfa/build-script-build` (exit status: 101)
  --- stdout
  Running command: "git submodule update --init" in dir: ../
  Submodule path 'librocksdb-sys/rocksdb': checked out 'f4441966592636253fd5ab0bb9ed44fc2697fc53'
  Submodule path 'librocksdb-sys/snappy': checked out '23b3286820105438c5dbb9bc22f1bb85c5812c8a'

  --- stderr
  Submodule 'rocksdb_sys/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'librocksdb-sys/rocksdb'
  Submodule 'rocksdb_sys/snappy' (https://github.com/google/snappy.git) registered for path 'librocksdb-sys/snappy'
  Cloning into 'rust-rocksdb/librocksdb-sys/rocksdb'...
  Cloning into 'rust-rocksdb/librocksdb-sys/snappy'...
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdbool.h' file not found
  thread 'main' panicked at 'unable to generate rocksdb bindings: ClangDiagnostic("rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdbool.h' file not found\n")', librocksdb-sys/build.rs:40:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: core::result::unwrap_failed
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::bindgen_rocksdb
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

From the error message, file `stdbool.h` is not found while generating the bindings, but I do have `stdbool.h` in my include path, it is right there:

```sh
$ file /usr/lib/gcc/x86_64-redhat-linux/13/include/stdbool.h
/usr/lib/gcc/x86_64-redhat-linux/13/include/stdbool.h: C source, ASCII text
```

And I can use it in a C program:

```sh
$ cat main.c
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    bool a = true;
    printf("%d", a == 1);

    exit(EXIT_SUCCESS);
}

$ gcc main.c

$ ./a.out
1%
```

And that `stdbool.h` is needed linked, using the `-M` option of `gcc` to let it print the linked files:

```sh
$ gcc main.c -M | grep stdbool.h
 /usr/lib/gcc/x86_64-redhat-linux/13/include/stdbool.h \
```

### My Spec

```sh
$ cat /etc/os-release | head -2
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"

$ uname -a
Linux fedora 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7)
```

I have RocksDB installed via my package manager, but it looks like this crate will download RocksDB from the git repo, so I guess this is not used.

**Comment by SteveLauC** [comment]
Well, I installed `clang`, which gives me another `stdbool.h` file, now I can compile this crate without any issues:

```sh
$ sudo dnf install clang

$ file /usr/include/c++/13/tr1/stdbool.h
/usr/include/c++/13/tr1/stdbool.h: C source, ASCII text
```

I guess installing `clang` gives me a `stdboo.h` for C++, while my gcc `stdboo.h` is for C, so it cannot work.
